### ISSUE TITLE
hotpot command not found

### ISSUE THREAD

**Issue by TylerHext** [erik/hotpot#1]
I'm trying to follow the Quick Start docs to test the app locally. After cloning the repository I'm unable to run `hotpot import` as the command is not recognized. 

`$ hotpot --help`

`zsh: command not found: hotpot`

Is there a step between cloning the repository and running the quick start that I am missing?

**Comment by TylerHext** [comment]
I resolved this with the following steps:

- Install Rust and Cargo via [these directions](https://doc.rust-lang.org/cargo/getting-started/installation.html)
- Run `cargo build` from the directory I cloned this repo into
- `cd target/debug`
- `./hotpot --help`

Is there a workaround so I don't need to prepend the hotpot command with `./` ? Is working from `src/debug` the proper workflow?

**Comment by erik** [comment]
Thanks for giving this a try! You might be the first person to go through the README other than myself, so you might encounter some rough edges.

Basically, you would need to move the built executable to somewhere on your `PATH`. Without knowing your particular environment, one option would be to `cp ./path/to/hotpot /usr/local/bin/hotpot`. 

I'd also suggest using `cargo build --release` and copying the executable from `./target/release` instead. I can update the README to make these steps more clear.

**Comment by TylerHext** [comment]
Worked perfectly. Thanks for the help!
