### ISSUE TITLE
Installation on portainer

### ISSUE THREAD

**Issue by MonolithNZ** [erik/hotpot#3]
Hi there,

I love your dÃ©rive app, and I'm tryin to get hotpot up and running on my Debian VM now :)

I'm very green when it comes to this stuff, so please bear with me.

I've made an image from your docker file and got it up and running on portainer. I have mounted /data to the location of the sqlite db. The logs say "2024-03-09T04:00:07.586128Z  INFO hotpot::web: starting server on http://0.0.0.0:8080" so I must me close! 

Then via the CLI when I try hotpot serve I get 

thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:79:13:
error binding to 127.0.0.1:8080: error creating server listener: Address already in use (os error 98)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This is a bit beyond me. I see the address is in use, So I tried editing the command "'--db' '/data/hotpot.sqlite3' 'serve' '--host' '0.0.0.0'" by changing the host to various other addresses with no luck.

Are you able to help point me in the right direction here? :)

**Comment by MonolithNZ** [comment]
I am able to import GPX files, It's purely the running of the webserver that I'm having issue with now

**Comment by MonolithNZ** [comment]
More progress, I see that you can call a different port ""hotpot serve -p 8484" did the trick! Thanks so much! Now to play with Strava integration

**Comment by MonolithNZ** [comment]
Alright, I'm really struggling here. So I've successfully imported 164 GPX files (starting activity import path="gpxsyno" num_known=164), but when I start the webserver they're not present on the map.

**Comment by erik** [comment]
Hey @MonolithNZ! Some quick questions to help debugging further:

- Are you also running the `import` command from within the Docker image? 
  - If so, is the `--db` path the same as for the `serve` command and `/data` mounted as a volume?
  - If not, did you copy the sqlite files (including `-shm` and `-wal` etc.) to wherever you're mounting `/data`?

Could you share more details about your setup? What commands you're running, how you're configuring the Docker container, etc.

**Comment by MonolithNZ** [comment]
Hi @erik , thanks for responding!

- I've created a docker image using your dockerfile. Docker is running on a Debian VM. I've tried running commands both from within the container and outside of it. 
- I have mounted /data as a volume. After my first import, I see there is an sqlite database there, along with the shm and wal file. I also see there is a database file,shm and wal in the root directory.
- From within the container, i use the 'hotpot import /import' command (/import is a bind to a location where my gpx files are). It successfully loads the 164 files ("2024-03-16T03:33:51.260488Z  INFO hotpot::activity: starting activity import path="/import" num_known=164")
- I then run hotpot serve -p 8484, to start the webserver. Port 8484 on the host is bound to port 8080 in the container settings on portainer
- When I load up the webserver in my browser, none of the GPX data is there.

I'm sorry if this isn't the info you were looking for, I'm very new to Docker/Linux etc, and there's tons of new concepts I'm trying to learn at once :) I know that I've successfully added the /data mount, because If I remove it and then restart the container the log says "ERROR r2d2: unable to open database file: /data/hotpot.sqlite3".

**Comment by erik** [comment]
Hey @MonolithNZ, sorry for the delay on responding. I've been making some usability improvements recently, and added support for adding activities directly from the browser, which might make the setup process easier if you're still interested in trying out the project. More details in the README, but after you pull the latest version, tl;dr is:

```
hotpot serve --upload

# Open the browser and open the file upload dialog by clicking the "Add activity
# files" button
open http://localhost:8080
```

Let me know if it works out for you!

**Comment by erik** [comment]
Closing older issues, feel free to reopen if this is still relevant
